//
//  Generated by @parlour/design. Do not edit: run `pnpm exec nx run design:emit`
//  after changing packages/design/src/tokens.ts, and commit what it writes.
//

import CoreGraphics
import Foundation

/// The palette, the type ramp and the state vocabulary, shared with the site,
/// the menu bar app and the phone page. See Theme.swift for the SwiftUI
/// wrappers that resolve a Duotone against the current colour scheme.
public enum ParlourTokens {
  /// A colour with a light and a dark value, as an RGB literal and an opacity.
  public struct Duotone: Sendable, Equatable {
    public let light: UInt32
    public let lightOpacity: Double
    public let dark: UInt32
    public let darkOpacity: Double
  }

  public enum Colour {
    public static let paper = Duotone(
      light: 0xEEF0EA, lightOpacity: 1.0,
      dark: 0x0F1F1B, darkOpacity: 1.0
    )
    public static let surface = Duotone(
      light: 0xF7F8F4, lightOpacity: 1.0,
      dark: 0x16302A, darkOpacity: 1.0
    )
    public static let ink = Duotone(
      light: 0x14312B, lightOpacity: 1.0,
      dark: 0xE7E9E2, darkOpacity: 1.0
    )
    public static let bracken = Duotone(
      light: 0x5F6F5E, lightOpacity: 1.0,
      dark: 0x9AA89A, darkOpacity: 1.0
    )
    public static let rule = Duotone(
      light: 0xCFD5CB, lightOpacity: 1.0,
      dark: 0x2B3F39, darkOpacity: 1.0
    )
    public static let inset = Duotone(
      light: 0xE3E7DE, lightOpacity: 1.0,
      dark: 0x17302A, darkOpacity: 1.0
    )
    public static let hearth = Duotone(
      light: 0x1C6B52, lightOpacity: 1.0,
      dark: 0x7ED3B0, darkOpacity: 1.0
    )
    public static let hearthInk = Duotone(
      light: 0xF7F8F4, lightOpacity: 1.0,
      dark: 0x0B2119, darkOpacity: 1.0
    )
    public static let lamp = Duotone(
      light: 0xE9B84A, lightOpacity: 1.0,
      dark: 0xE9B84A, darkOpacity: 1.0
    )
    public static let lampText = Duotone(
      light: 0x8A6112, lightOpacity: 1.0,
      dark: 0xE9B84A, darkOpacity: 1.0
    )
    public static let lampInk = Duotone(
      light: 0x2A2008, lightOpacity: 1.0,
      dark: 0x2A2008, darkOpacity: 1.0
    )
    public static let lampGlow = Duotone(
      light: 0xE9B84A, lightOpacity: 0.35,
      dark: 0xE9B84A, darkOpacity: 0.22
    )
    public static let alarm = Duotone(
      light: 0x9C3A2C, lightOpacity: 1.0,
      dark: 0xE59183, darkOpacity: 1.0
    )
    public static let alarmInk = Duotone(
      light: 0xF7F8F4, lightOpacity: 1.0,
      dark: 0x2A100B, darkOpacity: 1.0
    )
  }

  /// Which palette entry a state mark is drawn in.
  public enum ColourRole: String, Sendable, CaseIterable {
    case hearth
    case lamp
    case bracken
  }

  /// The states a session moves through, in order.
  public enum SessionState: String, Sendable, CaseIterable, Codable {
    case stopped
    case idle
    case listening
    case thinking
    case speaking
  }

  /// How a state is drawn: the colour, one full breath, and whether it is lit.
  public struct StateMark: Sendable, Equatable {
    public let colour: ColourRole
    /// One full breath in seconds, or nil for a mark that holds still.
    public let pulse: TimeInterval?
    public let filled: Bool
    public let glow: Bool
    public let label: String
  }

  public static func mark(for state: SessionState) -> StateMark {
    switch state {
      case .stopped:
        return StateMark(colour: .bracken, pulse: nil, filled: false, glow: false, label: "stopped")
      case .idle:
        return StateMark(colour: .hearth, pulse: nil, filled: true, glow: false, label: "ready")
      case .listening:
        return StateMark(colour: .hearth, pulse: 1.1, filled: true, glow: true, label: "listening")
      case .thinking:
        return StateMark(colour: .lamp, pulse: 0.7, filled: true, glow: true, label: "thinking")
      case .speaking:
        return StateMark(colour: .hearth, pulse: 0.5, filled: true, glow: true, label: "speaking")
    }
  }

  /// The ramp is in points at a 17pt base. Theme.swift turns these into fonts;
  /// the CSS font stacks have no meaning here, so they are not emitted.
  public enum Text {
    public static let micro: CGFloat = 12.0
    public static let small: CGFloat = 13.0
    public static let body: CGFloat = 15.0
    public static let lede: CGFloat = 17.0
    public static let title: CGFloat = 20.0
    public static let heading: CGFloat = 26.0
    public static let display: CGFloat = 40.0
  }

  public enum Leading {
    public static let tight: CGFloat = 1.15
    public static let snug: CGFloat = 1.3
    public static let normal: CGFloat = 1.55
  }

  public enum Space {
    public static let xs: CGFloat = 4.0
    public static let sm: CGFloat = 8.0
    public static let md: CGFloat = 12.0
    public static let lg: CGFloat = 16.0
    public static let xl: CGFloat = 24.0
    public static let xxl: CGFloat = 32.0
    public static let xxxl: CGFloat = 48.0
  }

  public enum Radius {
    public static let sm: CGFloat = 4.0
    public static let md: CGFloat = 6.0
    public static let lg: CGFloat = 10.0
    public static let full: CGFloat = 999.0
  }

  public enum Motion {
    public static let quick: TimeInterval = 0.12
    public static let settle: TimeInterval = 0.22
    public static let breath: TimeInterval = 0.7
  }

  /// The line weight of every rule in the interface.
  public static let hairline: CGFloat = 1.0
}
