/**
 * The tokens as CSS custom properties. One file, byte for byte the same in the
 * site, the menu bar app and the phone page, so a colour is never "nearly" the
 * same in two places. Each surface imports it and writes its own layout on top;
 * none of them declares a colour.
 */
import {
  hairline,
  leading,
  measure,
  motion,
  palette,
  radius,
  sessionStates,
  space,
  stateMarks,
  text,
  typography,
} from "./tokens.ts";

type Scheme = "light" | "dark";

/*
 * The property names deliberately avoid --font-*, --text-*, --leading-*,
 * --radius-*, --color-* and --spacing. Those are Tailwind's theme namespaces,
 * and the menu bar app loads this file next to Tailwind: a shared token with
 * one of those names would quietly redefine a Tailwind utility, or, for the
 * font stacks, declare itself in terms of itself. Hence face, type, line and
 * corner.
 */

/** Just the colours, which are the only tokens that change with the scheme. */
function colours(scheme: Scheme, indent: string): string {
  return Object.entries(palette)
    .map(([name, tone]) => `${indent}--${kebab(name)}: ${tone[scheme]};`)
    .join("\n");
}

function kebab(name: string): string {
  return name.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`);
}

/** Everything that does not care about light or dark. */
function invariants(): string {
  const lines: string[] = [];

  lines.push("  /* Type. The site prepends Young Serif to --face-serif; nothing else does. */");
  lines.push(`  --face-serif: ${typography.serif};`);
  lines.push(`  --face-sans: ${typography.sans};`);
  lines.push(`  --face-mono: ${typography.mono};`);
  lines.push("");
  for (const [name, size] of Object.entries(text)) lines.push(`  --type-${name}: ${size}px;`);
  lines.push("");
  for (const [name, value] of Object.entries(leading)) lines.push(`  --line-${name}: ${value};`);

  lines.push("");
  lines.push("  /* A 4pt grid. */");
  for (const [name, value] of Object.entries(space)) lines.push(`  --space-${name}: ${value}px;`);

  lines.push("");
  for (const [name, value] of Object.entries(radius)) lines.push(`  --corner-${name}: ${value}px;`);

  lines.push("");
  for (const [name, value] of Object.entries(motion)) lines.push(`  --motion-${name}: ${value}ms;`);

  lines.push("");
  lines.push(`  --hairline: ${hairline}px;`);
  lines.push(`  --measure-prose: ${measure.prose}rem;`);
  lines.push(`  --measure-doc: ${measure.doc}rem;`);

  lines.push("");
  lines.push("  /* The session states, as a colour and a breath. 0ms is a mark that holds still. */");
  for (const state of sessionStates) {
    const mark = stateMarks[state];
    lines.push(`  --state-${state}: var(--${kebab(mark.colour)});`);
    lines.push(`  --state-${state}-pulse: ${mark.pulseMs ?? 0}ms;`);
  }

  return lines.join("\n");
}

export const cssBanner =
  "/*\n" +
  " * Generated by @parlour/design. Do not edit: run `pnpm exec nx run design:emit`\n" +
  " * after changing packages/design/src/tokens.ts, and commit what it writes.\n" +
  " */";

export function emitCss(): string {
  return `${cssBanner}

:root {
  color-scheme: light dark;

  /* The wall, the ink and the two colours that mean something. */
${colours("light", "  ")}

${invariants()}
}

/*
 * Dark is the same room with the lamp doing more of the work. The guard lets a
 * surface pin itself to light (the menu bar app follows the system, the site
 * follows the browser, and either can be overridden with data-theme).
 */
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${colours("dark", "    ")}
  }
}

:root[data-theme="dark"],
.dark {
${colours("dark", "  ")}
}
`;
}
