/**
 * The same tokens as Swift, for the iOS app. The generated file holds raw
 * values and nothing else; turning a duotone into a SwiftUI `Color` that
 * follows the trait collection is the hand-written Theme's job, because that
 * is a platform decision rather than a design one.
 */
import {
  hairline,
  leading,
  motion,
  palette,
  radius,
  sessionStates,
  space,
  stateMarks,
  text,
} from "./tokens.ts";

/** `#rrggbb` or `rgba(r, g, b, a)` as a 0xRRGGBB literal and an opacity. */
function parse(value: string): { hex: string; opacity: number } {
  const rgba = value.match(/^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*(?:,\s*([\d.]+)\s*)?\)$/);
  if (rgba) {
    const [r, g, b] = [rgba[1], rgba[2], rgba[3]].map((part) => Number(part));
    const hex = ((r! << 16) | (g! << 8) | b!).toString(16).padStart(6, "0").toUpperCase();
    return { hex: `0x${hex}`, opacity: rgba[4] === undefined ? 1 : Number(rgba[4]) };
  }
  const hex = value.match(/^#([0-9a-fA-F]{6})$/);
  if (!hex) throw new Error(`Cannot express ${value} as a Swift colour literal`);
  return { hex: `0x${hex[1]!.toUpperCase()}`, opacity: 1 };
}

/** Swift cares about 1 versus 1.0, and every token here is a floating point one. */
function double(value: number): string {
  return Number.isInteger(value) ? `${value}.0` : `${value}`;
}

export const swiftBanner =
  "//\n" +
  "//  Generated by @parlour/design. Do not edit: run `pnpm exec nx run design:emit`\n" +
  "//  after changing packages/design/src/tokens.ts, and commit what it writes.\n" +
  "//";

export function emitSwift(): string {
  const colours = Object.entries(palette)
    .map(([name, tone]) => {
      const light = parse(tone.light);
      const dark = parse(tone.dark);
      return (
        `    public static let ${name} = Duotone(\n` +
        `      light: ${light.hex}, lightOpacity: ${double(light.opacity)},\n` +
        `      dark: ${dark.hex}, darkOpacity: ${double(dark.opacity)}\n` +
        "    )"
      );
    })
    .join("\n");

  const marks = sessionStates
    .map((state) => {
      const mark = stateMarks[state];
      const pulse = mark.pulseMs === null ? "nil" : double(mark.pulseMs / 1000);
      return (
        `      case .${state}:\n` +
        `        return StateMark(colour: .${mark.colour}, pulse: ${pulse}, ` +
        `filled: ${mark.filled}, glow: ${mark.glow}, label: "${mark.label}")`
      );
    })
    .join("\n");

  const sizes = Object.entries(text)
    .map(([name, size]) => `    public static let ${name}: CGFloat = ${double(size)}`)
    .join("\n");

  const leadings = Object.entries(leading)
    .map(([name, value]) => `    public static let ${name}: CGFloat = ${double(value)}`)
    .join("\n");

  const spaces = Object.entries(space)
    .map(([name, value]) => `    public static let ${name}: CGFloat = ${double(value)}`)
    .join("\n");

  const radii = Object.entries(radius)
    .map(([name, value]) => `    public static let ${name}: CGFloat = ${double(value)}`)
    .join("\n");

  const motions = Object.entries(motion)
    .map(([name, value]) => `    public static let ${name}: TimeInterval = ${double(value / 1000)}`)
    .join("\n");

  return `${swiftBanner}

import CoreGraphics
import Foundation

/// The palette, the type ramp and the state vocabulary, shared with the site,
/// the menu bar app and the phone page. See Theme.swift for the SwiftUI
/// wrappers that resolve a Duotone against the current colour scheme.
public enum ParlourTokens {
  /// A colour with a light and a dark value, as an RGB literal and an opacity.
  public struct Duotone: Sendable, Equatable {
    public let light: UInt32
    public let lightOpacity: Double
    public let dark: UInt32
    public let darkOpacity: Double
  }

  public enum Colour {
${colours}
  }

  /// Which palette entry a state mark is drawn in.
  public enum ColourRole: String, Sendable, CaseIterable {
    case hearth
    case lamp
    case bracken
  }

  /// The states a session moves through, in order.
  public enum SessionState: String, Sendable, CaseIterable, Codable {
${sessionStates.map((state) => `    case ${state}`).join("\n")}
  }

  /// How a state is drawn: the colour, one full breath, and whether it is lit.
  public struct StateMark: Sendable, Equatable {
    public let colour: ColourRole
    /// One full breath in seconds, or nil for a mark that holds still.
    public let pulse: TimeInterval?
    public let filled: Bool
    public let glow: Bool
    public let label: String
  }

  public static func mark(for state: SessionState) -> StateMark {
    switch state {
${marks}
    }
  }

  /// The ramp is in points at a 17pt base. Theme.swift turns these into fonts;
  /// the CSS font stacks have no meaning here, so they are not emitted.
  public enum Text {
${sizes}
  }

  public enum Leading {
${leadings}
  }

  public enum Space {
${spaces}
  }

  public enum Radius {
${radii}
  }

  public enum Motion {
${motions}
  }

  /// The line weight of every rule in the interface.
  public static let hairline: CGFloat = ${double(hairline)}
}
`;
}
